In [7]:
#np.sort()
import numpy as np
a = np.random.randint(1,100,15)

In [8]:
a

array([26, 66, 83, 75, 90, 21, 19,  9, 19, 99, 48, 74, 29, 64, 58])

In [11]:
np.sort(a)[::-1]

array([99, 90, 83, 75, 74, 66, 64, 58, 48, 29, 26, 21, 19, 19,  9])

In [12]:
b= np.random.randint(1,100,24).reshape(6,4)

In [13]:
b

array([[ 9, 94, 92, 78],
       [76, 85, 83,  8],
       [43, 94, 13, 64],
       [24, 54, 70,  6],
       [17, 77, 81, 12],
       [87, 10, 25, 28]])

In [15]:
np.sort(b, axis = 1)

array([[ 9, 78, 92, 94],
       [ 8, 76, 83, 85],
       [13, 43, 64, 94],
       [ 6, 24, 54, 70],
       [12, 17, 77, 81],
       [10, 25, 28, 87]])

In [16]:
a

array([26, 66, 83, 75, 90, 21, 19,  9, 19, 99, 48, 74, 29, 64, 58])

In [17]:
np.append(a,200)

array([ 26,  66,  83,  75,  90,  21,  19,   9,  19,  99,  48,  74,  29,
        64,  58, 200])

In [27]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[ 9., 94., 92., 78.,  1.],
       [76., 85., 83.,  8.,  1.],
       [43., 94., 13., 64.,  1.],
       [24., 54., 70.,  6.,  1.],
       [17., 77., 81., 12.,  1.],
       [87., 10., 25., 28.,  1.]])

In [29]:
c = np.arange(0,24).reshape(6,4)

In [30]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
np.concatenate((c,b),axis = 1)

array([[ 0,  1,  2,  3,  9, 94, 92, 78],
       [ 4,  5,  6,  7, 76, 85, 83,  8],
       [ 8,  9, 10, 11, 43, 94, 13, 64],
       [12, 13, 14, 15, 24, 54, 70,  6],
       [16, 17, 18, 19, 17, 77, 81, 12],
       [20, 21, 22, 23, 87, 10, 25, 28]])

In [34]:
np.where(a>50)

(array([ 1,  2,  3,  4,  9, 11, 13, 14]),)

In [35]:
np.where(a>50, 0, a)

array([26,  0,  0,  0,  0, 21, 19,  9, 19,  0, 48,  0, 29,  0,  0])

In [36]:
np.argmax(a)

9

In [38]:
b

array([[ 9, 94, 92, 78],
       [76, 85, 83,  8],
       [43, 94, 13, 64],
       [24, 54, 70,  6],
       [17, 77, 81, 12],
       [87, 10, 25, 28]])

In [40]:
np.argmax(b,axis = 1)

array([1, 1, 1, 2, 2, 0])

In [41]:
np.argmin(a)

7

In [42]:
a

array([26, 66, 83, 75, 90, 21, 19,  9, 19, 99, 48, 74, 29, 64, 58])

In [43]:
np.cumsum(a)

array([ 26,  92, 175, 250, 340, 361, 380, 389, 408, 507, 555, 629, 658,
       722, 780])

In [44]:
np.cumprod(a)

array([                  26,                 1716,               142428,
                   10682100,            961389000,          20189169000,
               383594211000,        3452347899000,       65594610081000,
           6493866398019000,   311705587104912000,  4619469372053936384,
        4837403273597293824, -4000839742835572736,  7758967873760952320])

In [45]:
np.cumsum(b)

array([   9,  103,  195,  273,  349,  434,  517,  525,  568,  662,  675,
        739,  763,  817,  887,  893,  910,  987, 1068, 1080, 1167, 1177,
       1202, 1230])

In [47]:
print(b)
np.cumsum(b, axis = 0)

[[ 9 94 92 78]
 [76 85 83  8]
 [43 94 13 64]
 [24 54 70  6]
 [17 77 81 12]
 [87 10 25 28]]


array([[  9,  94,  92,  78],
       [ 85, 179, 175,  86],
       [128, 273, 188, 150],
       [152, 327, 258, 156],
       [169, 404, 339, 168],
       [256, 414, 364, 196]])

In [48]:
a

array([26, 66, 83, 75, 90, 21, 19,  9, 19, 99, 48, 74, 29, 64, 58])

In [49]:
items= [10,20,30,40,50,60,70,80,90,100]

In [51]:
a[np.isin(a,items)]

array([90])

In [52]:
a

array([26, 66, 83, 75, 90, 21, 19,  9, 19, 99, 48, 74, 29, 64, 58])

In [53]:
np.put(a, [1,5],[73,67])

In [54]:
a

array([26, 73, 83, 75, 90, 67, 19,  9, 19, 99, 48, 74, 29, 64, 58])

In [55]:
np.delete(a, 4)

array([26, 73, 83, 75, 67, 19,  9, 19, 99, 48, 74, 29, 64, 58])

In [56]:
b

array([[ 9, 94, 92, 78],
       [76, 85, 83,  8],
       [43, 94, 13, 64],
       [24, 54, 70,  6],
       [17, 77, 81, 12],
       [87, 10, 25, 28]])

In [57]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [61]:
np.intersect1d(b,c)

array([ 6,  8,  9, 10, 12, 13, 17])

In [63]:
b

array([[ 9, 94, 92, 78],
       [76, 85, 83,  8],
       [43, 94, 13, 64],
       [24, 54, 70,  6],
       [17, 77, 81, 12],
       [87, 10, 25, 28]])

In [62]:
np.clip(b, a_min = 25, a_max = 75)

array([[25, 75, 75, 75],
       [75, 75, 75, 25],
       [43, 75, 25, 64],
       [25, 54, 70, 25],
       [25, 75, 75, 25],
       [75, 25, 25, 28]])